[features]
seeds = false
[programs.devnet]
mycooldapp = "7LHwZUsWaTXai5rVoHcoQPpTNC5pq3XoyWoLd6VUXf1N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "node tests/mycooldapp.js"
